In [1]:
import pandas as pd
data4={'emp_id':[101,102,103,104],
      'salary':[234,345,200,400],
      'pf':[23,34,56,78]}

In [4]:
data5={'emp_id':[101,102,104,105],
    'mob_no':[3434,5434,767,878],
    'house_nu':[345,345,345,56]
}

In [5]:
df4=pd.DataFrame(data4)

In [6]:
df5=pd.DataFrame(data5)

In [7]:
df4

emp_id  salary  pf
0     101     234  23
1     102     345  34
2     103     200  56
3     104     400  78

In [8]:
df5

emp_id  mob_no  house_nu
0     101    3434       345
1     102    5434       345
2     104     767       345
3     105     878        56

In [9]:
pd.merge(df4,df5)# Common Data in Common Column name

emp_id  salary  pf  mob_no  house_nu
0     101     234  23    3434       345
1     102     345  34    5434       345
2     104     400  78     767       345

In [12]:
pd.merge(df4,df5,how='left')# Left Join 

emp_id  salary  pf  mob_no  house_nu
0     101     234  23  3434.0     345.0
1     102     345  34  5434.0     345.0
2     103     200  56     NaN       NaN
3     104     400  78   767.0     345.0

In [13]:
pd.merge(df4,df5,how='right')

emp_id  salary    pf  mob_no  house_nu
0     101   234.0  23.0    3434       345
1     102   345.0  34.0    5434       345
2     104   400.0  78.0     767       345
3     105     NaN   NaN     878        56

In [14]:
pd.merge(df4,df5,how='right',on='emp_id')

emp_id  salary    pf  mob_no  house_nu
0     101   234.0  23.0    3434       345
1     102   345.0  34.0    5434       345
2     104   400.0  78.0     767       345
3     105     NaN   NaN     878        56

In [16]:
data6={'emp_id1':[101,102,103,104],
      'salary':[234,345,200,400],
      'pf':[23,34,56,78]}
data7={'emp_id2':[101,102,104,105],
    'mob_no':[3434,5434,767,878],
    'house_nu':[345,345,345,56]
}

In [17]:
df6=pd.DataFrame(data6)

In [19]:
df7=pd.DataFrame(data7)

In [20]:
pd.merge(df6,df7)

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

In [22]:
pd.merge(df6,df7,left_on='emp_id1',right_on='emp_id2',how='inner')

emp_id1  salary  pf  emp_id2  mob_no  house_nu
0      101     234  23      101    3434       345
1      102     345  34      102    5434       345
2      104     400  78      104     767       345

In [25]:
data8={'emp_id':[101,102,103,104],
      'salary':[234,345,200,400],
      'pf':[23,34,56,78]}
data9={'emp_id':[101,102,104,105],
    'salary':[234,345,200,400],
    'house_nu':[345,345,345,56]
}

In [26]:
df8=pd.DataFrame(data8)

In [27]:
df9=pd.DataFrame(data9)

In [28]:
df8

emp_id  salary  pf
0     101     234  23
1     102     345  34
2     103     200  56
3     104     400  78

In [29]:
df9

emp_id  salary  house_nu
0     101     234       345
1     102     345       345
2     104     200       345
3     105     400        56

In [30]:
pd.merge(df8,df9,on=['emp_id','salary'])

emp_id  salary  pf  house_nu
0     101     234  23       345
1     102     345  34       345

In [46]:
data10={'emp_id1':[101,102,103,104],
      'salary1':[234,345,200,400],
      'pf':[23,34,56,78]}
data11={'emp_id2':[101,102,104,105,123],
    'salary2':[234,345,200,400,43],
    'house_nu':[345,345,345,56,234]
}
df10=pd.DataFrame(data10,index=['a','b','c','d'])
df11=pd.DataFrame(data11,index=['a','b','d','e','f'])

In [47]:
df10

emp_id1  salary1  pf
a      101      234  23
b      102      345  34
c      103      200  56
d      104      400  78

In [48]:
df11

emp_id2  salary2  house_nu
a      101      234       345
b      102      345       345
d      104      200       345
e      105      400        56
f      123       43       234

In [49]:
df10.join(df11)

emp_id1  salary1  pf  emp_id2  salary2  house_nu
a      101      234  23    101.0    234.0     345.0
b      102      345  34    102.0    345.0     345.0
c      103      200  56      NaN      NaN       NaN
d      104      400  78    104.0    200.0     345.0

In [55]:
df_sales=pd.read_csv(r'C:\\Users\dell\Downloads\sales_data_final.csv')

In [56]:
df_sales

order_id  order_date ship_date       ship_mode  \
0         AG-2011-2040    1/1/2011  1/6/2011  Standard Class   
1        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
2         HU-2011-1220    1/1/2011  1/5/2011    Second Class   
3      IT-2011-3647632    1/1/2011  1/5/2011    Second Class   
4        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
...                ...         ...       ...             ...   
51285   CA-2014-115427  12/31/2014  1/4/2015  Standard Class   
51286     MO-2014-2560  12/31/2014  1/5/2015  Standard Class   
51287   MX-2014-110527  12/31/2014  1/2/2015    Second Class   
51288   MX-2014-114783  12/31/2014  1/6/2015  Standard Class   
51289   CA-2014-156720  12/31/2014  1/4/2015  Standard Class   

          customer_name      segment             state        country  market  \
0       Toby Braunhardt     Consumer       Constantine        Algeria  Africa   
1           Joseph Holt     Consumer   New South Wales      Australia    APAC   
2         Annie Thurman     Consumer          Budapest        Hungary    EMEA   
3          Eugene Moren  Home Office         Stockholm         Sweden      EU   
4           Joseph Holt     Consumer   New South Wales      Australia    APAC   
...                 ...          ...               ...            ...     ...   
51285        Erica Bern    Corporate        California  United States      US   
51286         Liz Preis     Consumer  Souss-Massa-Draƒ        Morocco  Africa   
51287  Charlotte Melton     Consumer           Managua      Nicaragua   LATAM   
51288     Tamara Dahlen     Consumer         Chihuahua         Mexico   LATAM   
51289     Jill Matthias     Consumer          Colorado  United States      US   

        region  ...         category sub_category  \
0       Africa  ...  Office Supplies      Storage   
1      Oceania  ...  Office Supplies     Supplies   
2         EMEA  ...  Office Supplies      Storage   
3        North  ...  Office Supplies        Paper   
4      Oceania  ...        Furniture  Furnishings   
...        ...  ...              ...          ...   
51285     West  ...  Office Supplies      Binders   
51286   Africa  ...  Office Supplies      Binders   
51287  Central  ...  Office Supplies       Labels   
51288    North  ...  Office Supplies       Labels   
51289     West  ...  Office Supplies    Fasteners   

                                          product_name sales quantity  \
0                                  Tenex Lockers, Blue   408        2   
1                             Acme Trimmer, High Speed   120        3   
2                              Tenex Box, Single Width    66        4   
3                          Enermax Note Cards, Premium    45        3   
4                           Eldon Light Bulb, Duo Pack   114        5   
...                                                ...   ...      ...   
51285  Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl    14        2   
51286          Wilson Jones Hole Reinforcements, Clear     4        1   
51287           Hon Color Coded Labels, 5000 Label Set    26        3   
51288           Hon Legal Exhibit Labels, Alphabetical     7        1   
51289                              Bagged Rubber Bands     3        3   

       discount    profit  shipping_cost  order_priority  year  
0           0.0  106.1400          35.46          Medium  2011  
1           0.1   36.0360           9.72          Medium  2011  
2           0.0   29.6400           8.17            High  2011  
3           0.5  -26.0550           4.82            High  2011  
4           0.1   37.7700           4.70          Medium  2011  
...         ...       ...            ...             ...   ...  
51285       0.2    4.5188           0.89          Medium  2014  
51286       0.0    0.4200           0.49          Medium  2014  
51287       0.0   12.3600           0.35          Medium  2014  
51288       0.0    0.5600           0.20          Medium  2014  
51289       0.2   -0.6048           0.17   

In [57]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

          category sub_category                 product_name sales quantity  \
0  Office Supplies      Storage          Tenex Lockers, Blue   408        2   
1  Office Supplies     Supplies     Acme Trimmer, High Speed   120        3   
2  Office Supplies      Storage      Tenex Box, Single Width    66        4   
3  Office Supplies        Paper  Enermax Note Cards, Premium    45        3   
4        Furniture  Furnishings   Eldon Light Bulb, Duo Pack   114        5   

   discount   profit  shipping_cost  order_priority  year  
0       0.0  106.140          35.46          Medium  2011  
1       0.1   36.036           9.72          Medium  2011  
2       0.0   29.640           8.17            High  2011  
3       0.5  -26.055           4.82            High  2011  
4       0.1   37.770           4.70          Medium  2011  

[5 rows x 21 columns]

In [58]:
def profit_flag(a):
    if a>=0:
        return 'positive'
    else:
        return 'negative'

In [59]:
profit_flag(-12)

'negative'

In [60]:
profit_flag(12)

'positive'

In [61]:
df_sales['flag_profit']=df_sales['profit'].apply(profit_flag)# Create Derived Column using apply

In [62]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... sub_category  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...      Storage   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...     Supplies   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...      Storage   
3  Home Office        Stockholm     Sweden      EU    North  ...        Paper   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...  Furnishings   

                  product_name sales quantity discount   profit  \
0          Tenex Lockers, Blue   408        2      0.0  106.140   
1     Acme Trimmer, High Speed   120        3      0.1   36.036   
2      Tenex Box, Single Width    66        4      0.0   29.640   
3  Enermax Note Cards, Premium    45        3      0.5  -26.055   
4   Eldon Light Bulb, Duo Pack   114        5      0.1   37.770   

   shipping_cost  order_priority  year flag_profit  
0          35.46          Medium  2011    positive  
1           9.72          Medium  2011    positive  
2           8.17            High  2011    positive  
3           4.82            High  2011    negative  
4           4.70          Medium  2011    positive  

[5 rows x 22 columns]

In [64]:
df_sales['Customer_Name_Length']=df_sales['customer_name'].apply(len)

In [65]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

                  product_name sales quantity discount   profit  \
0          Tenex Lockers, Blue   408        2      0.0  106.140   
1     Acme Trimmer, High Speed   120        3      0.1   36.036   
2      Tenex Box, Single Width    66        4      0.0   29.640   
3  Enermax Note Cards, Premium    45        3      0.5  -26.055   
4   Eldon Light Bulb, Duo Pack   114        5      0.1   37.770   

   shipping_cost  order_priority  year  flag_profit Customer_Name_Length  
0          35.46          Medium  2011     positive                   15  
1           9.72          Medium  2011     positive                   11  
2           8.17            High  2011     positive                   13  
3           4.82            High  2011     negative                   12  
4           4.70          Medium  2011     positive                   11  

[5 rows x 23 columns]

In [66]:
def Quantity_type(a):
    if a<10:
        return 'low'
    elif a>10 and a<20:
        return 'Medium'
    else:
        return 'High'

In [67]:
df_sales['Flag_Quantity']=df_sales['quantity'].apply(Quantity_type)

In [69]:
df_sales['Flag_Quantity'].value_counts()

low       50413
Medium      601
High        276
Name: Flag_Quantity, dtype: int64

In [72]:
df_sales['square_quantity']=df_sales['quantity'].apply(lambda a:a**2)

In [73]:
df_sales

order_id  order_date ship_date       ship_mode  \
0         AG-2011-2040    1/1/2011  1/6/2011  Standard Class   
1        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
2         HU-2011-1220    1/1/2011  1/5/2011    Second Class   
3      IT-2011-3647632    1/1/2011  1/5/2011    Second Class   
4        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
...                ...         ...       ...             ...   
51285   CA-2014-115427  12/31/2014  1/4/2015  Standard Class   
51286     MO-2014-2560  12/31/2014  1/5/2015  Standard Class   
51287   MX-2014-110527  12/31/2014  1/2/2015    Second Class   
51288   MX-2014-114783  12/31/2014  1/6/2015  Standard Class   
51289   CA-2014-156720  12/31/2014  1/4/2015  Standard Class   

          customer_name      segment             state        country  market  \
0       Toby Braunhardt     Consumer       Constantine        Algeria  Africa   
1           Joseph Holt     Consumer   New South Wales      Australia    APAC   
2         Annie Thurman     Consumer          Budapest        Hungary    EMEA   
3          Eugene Moren  Home Office         Stockholm         Sweden      EU   
4           Joseph Holt     Consumer   New South Wales      Australia    APAC   
...                 ...          ...               ...            ...     ...   
51285        Erica Bern    Corporate        California  United States      US   
51286         Liz Preis     Consumer  Souss-Massa-Draƒ        Morocco  Africa   
51287  Charlotte Melton     Consumer           Managua      Nicaragua   LATAM   
51288     Tamara Dahlen     Consumer         Chihuahua         Mexico   LATAM   
51289     Jill Matthias     Consumer          Colorado  United States      US   

        region  ... quantity discount    profit shipping_cost order_priority  \
0       Africa  ...        2      0.0  106.1400         35.46         Medium   
1      Oceania  ...        3      0.1   36.0360          9.72         Medium   
2         EMEA  ...        4      0.0   29.6400          8.17           High   
3        North  ...        3      0.5  -26.0550          4.82           High   
4      Oceania  ...        5      0.1   37.7700          4.70         Medium   
...        ...  ...      ...      ...       ...           ...            ...   
51285     West  ...        2      0.2    4.5188          0.89         Medium   
51286   Africa  ...        1      0.0    0.4200          0.49         Medium   
51287  Central  ...        3      0.0   12.3600          0.35         Medium   
51288    North  ...        1      0.0    0.5600          0.20         Medium   
51289     West  ...        3      0.2   -0.6048          0.17         Medium   

       year  flag_profit  Customer_Name_Length  Flag_Quantity square_quantity  
0      2011     positive                    15            low               4  
1      2011     positive                    11            low               9  
2      2011     positive                    13            low              16  
3      2011     negative                    12            low               9  
4      2011     positive                    11            low              25  
...     ...          ...                   ...            ...             ...  
51285  2014     positive                    10            low               4  
51286  2014     positive                     9            low               1  
51287  2014     positive                    16            low               9  
51288  2014     positive                    13            low               1  
51289  2014     negative                    13            low               9  

[51290 rows x 25 columns]

In [74]:
import numpy as np

In [75]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [76]:
type(np.array([1,2,3,4]))

numpy.ndarray

In [80]:
np.array([[2,3,4] , [3,4,5]])

array([[2, 3, 4],
       [3, 4, 5]])

In [82]:
l=[[1,2,3],[4,5,6]]

In [83]:
l[1][1]

5

In [86]:
a=np.array([3,4,5,6],ndmin=5)# 5 Dimension array using ndmin

In [87]:
a

array([[[[[3, 4, 5, 6]]]]])

In [88]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [89]:
arr.ndim# Gives Dimension of Array 

2

In [90]:
np.random.randint(1,10,(4,4))# 4*4 Matrix

array([[2, 5, 9, 8],
       [4, 1, 8, 3],
       [5, 7, 4, 5],
       [5, 5, 6, 6]])

In [93]:
np.random.randint(1,10,(4,4,2))# 4 tmes 4*2 Matrix

array([[[6, 5],
        [5, 3],
        [3, 3],
        [7, 5]],

       [[9, 9],
        [1, 4],
        [8, 8],
        [9, 1]],

       [[9, 3],
        [3, 9],
        [9, 1],
        [7, 2]],

       [[2, 8],
        [6, 3],
        [7, 1],
        [4, 6]]])

#Tasks 1
1.Read this DataSet in Pandas MYSQL And MongoDB
2.While Creating Table in MYSQL donot use Manula Approx to create it  alwys Use automation
### use csv kit library to automate this task and load the data in bulk in your mysql
3.comvert all the datesavailable in dataset to ime Stamp format in Pandas and in sql 
