In [2]:
import numpy as np

In [3]:
l=[1,2,3,4,5]

In [4]:
np.array(l)# all are integer 

array([1, 2, 3, 4, 5])

In [5]:
l1=[1,'ragh',3,4,5]

In [6]:
np.array(l1)# all data is String 

array(['1', 'ragh', '3', '4', '5'], dtype='<U11')

In [7]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
np.random.randint(2,5)

4

In [34]:
a2=np.random.randint(2,50,(3,4))# num btw 2 and 50 and matrix 3*4

In [14]:
np.random.randint(2,50,(2,3,4))# three dimentional 2 matrix of 3*4 

array([[[42, 20, 17, 46],
        [42,  7, 34, 12],
        [16,  5, 21, 21]],

       [[45, 16, 35, 24],
        [43, 39, 49, 47],
        [28, 25, 12, 28]]])

In [19]:
np.random.rand(2,3)# no between  0 to 1 in matrix 2* 3

array([[0.85130638, 0.24699019, 0.88843451],
       [0.13852274, 0.38744173, 0.8155767 ]])

In [20]:
np.random.randn(4,6)# number between -1 to 1 in matrix 4*6 avg =0 and sd =1  then it Standard Normal Distribution 

array([[ 0.11866527,  0.94772057, -0.86125447, -0.28321231, -0.42035212,
        -0.42672074],
       [-0.5711177 ,  0.01423592,  0.37292116, -0.23247988,  0.8108867 ,
         0.71330568],
       [ 0.75326244,  2.29639123, -0.6405905 , -0.96343406,  0.04939472,
         1.57756629],
       [ 0.67327628,  0.79317217,  0.48676354,  1.1289681 , -0.0309709 ,
         0.36707192]])

In [22]:
a4=np.random.randn(4,4)

In [24]:
a4.reshape(2,8)# to reshape the matrix 

array([[ 0.81893534, -0.77902797,  0.35769793, -0.5336047 , -0.55182534,
         0.94487143,  0.62666771, -1.38978089],
       [ 0.12595967, -0.06594398, -0.11071763, -0.21862138,  2.2177932 ,
         1.45883578, -0.52211595, -0.41317584]])

In [25]:
a4.size

16

In [26]:
a4.reshape(8,2)# to reshape the matrix 

array([[ 0.81893534, -0.77902797],
       [ 0.35769793, -0.5336047 ],
       [-0.55182534,  0.94487143],
       [ 0.62666771, -1.38978089],
       [ 0.12595967, -0.06594398],
       [-0.11071763, -0.21862138],
       [ 2.2177932 ,  1.45883578],
       [-0.52211595, -0.41317584]])

In [29]:
a4.reshape(8,-1)# autmatically take another demension not only -1 any negative number

array([[ 0.81893534, -0.77902797],
       [ 0.35769793, -0.5336047 ],
       [-0.55182534,  0.94487143],
       [ 0.62666771, -1.38978089],
       [ 0.12595967, -0.06594398],
       [-0.11071763, -0.21862138],
       [ 2.2177932 ,  1.45883578],
       [-0.52211595, -0.41317584]])

In [31]:
a4.reshape(2,2,4)# Change it into three dimension

array([[[ 0.81893534, -0.77902797,  0.35769793, -0.5336047 ],
        [-0.55182534,  0.94487143,  0.62666771, -1.38978089]],

       [[ 0.12595967, -0.06594398, -0.11071763, -0.21862138],
        [ 2.2177932 ,  1.45883578, -0.52211595, -0.41317584]]])

In [32]:
a3

NameError: name 'a3' is not defined

In [33]:
a2

NameError: name 'a2' is not defined

In [35]:
a2

array([[44, 35, 11, 48],
       [11, 23, 48, 43],
       [ 2, 21, 40, 34]])

In [38]:
a2[1:3,2:]

array([[48, 43],
       [40, 34]])

In [40]:
a5=np.random.randint(2,9,(6,5))

In [41]:
a5

array([[7, 3, 8, 7, 5],
       [3, 7, 6, 7, 3],
       [4, 4, 5, 2, 8],
       [6, 4, 8, 4, 4],
       [4, 7, 3, 8, 4],
       [5, 3, 8, 6, 5]])

In [42]:
a5[a5>4]# Condition under the array

array([7, 8, 7, 5, 7, 6, 7, 5, 8, 6, 8, 7, 8, 5, 8, 6, 5])

In [43]:
a5

array([[7, 3, 8, 7, 5],
       [3, 7, 6, 7, 3],
       [4, 4, 5, 2, 8],
       [6, 4, 8, 4, 4],
       [4, 7, 3, 8, 4],
       [5, 3, 8, 6, 5]])

In [44]:
a5[0][2]=12

In [45]:
a5

array([[ 7,  3, 12,  7,  5],
       [ 3,  7,  6,  7,  3],
       [ 4,  4,  5,  2,  8],
       [ 6,  4,  8,  4,  4],
       [ 4,  7,  3,  8,  4],
       [ 5,  3,  8,  6,  5]])

In [46]:
a5[0,1]

3

In [47]:
a5[0,1]=799

In [48]:
a5

array([[  7, 799,  12,   7,   5],
       [  3,   7,   6,   7,   3],
       [  4,   4,   5,   2,   8],
       [  6,   4,   8,   4,   4],
       [  4,   7,   3,   8,   4],
       [  5,   3,   8,   6,   5]])

In [54]:
a6=np.random.randint(0,3,(3,3))

In [55]:
a6

array([[0, 1, 2],
       [2, 0, 1],
       [1, 2, 1]])

In [56]:
a7=np.random.randint(0,3,(3,3))

In [57]:
a7

array([[0, 1, 1],
       [2, 2, 1],
       [0, 1, 1]])

In [60]:
a6*a7# do simple multiplication as simpe not do matrix multiplication

array([[0, 1, 2],
       [4, 0, 1],
       [0, 2, 1]])

In [61]:
a8=np.array([[1,2],[3,4]])

In [62]:
a9=np.array([[1,2,4],[6,1,1]])

In [64]:
a6@a7# Matrix multiplication

array([[2, 4, 3],
       [0, 3, 3],
       [4, 6, 4]])

In [67]:
a6.dot(a7)# matrix multiplication

array([[2, 4, 3],
       [0, 3, 3],
       [4, 6, 4]])

In [68]:
a6+100 # add 100 to each element

array([[100, 101, 102],
       [102, 100, 101],
       [101, 102, 101]])

In [69]:
a6*2 # multiply by2 to each element

array([[0, 2, 4],
       [4, 0, 2],
       [2, 4, 2]])

In [71]:
a6/0# divide by Zsro with ech elemnt 

<ipython-input-71-70bf32748b2e>:1: RuntimeWarning: divide by zero encountered in true_divide
  a6/0# divide by Zsro with ech elemnt
<ipython-input-71-70bf32748b2e>:1: RuntimeWarning: invalid value encountered in true_divide
  a6/0# divide by Zsro with ech elemnt


array([[nan, inf, inf],
       [inf, nan, inf],
       [inf, inf, inf]])

In [72]:
a6**3

array([[0, 1, 8],
       [8, 0, 1],
       [1, 8, 1]], dtype=int32)

In [75]:
np.zeros((3,3))# 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [76]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [77]:
a8=np.zeros((4,4))

In [78]:
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [80]:
a9=np.ones((4,5))

In [81]:
a9+10

array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]])

In [83]:
a9+np.array([1,2,3,4,5])# row wise addition to each row of a9

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [84]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [86]:
np.array([[1,2,3,4]]).T

array([[1],
       [2],
       [3],
       [4]])

In [88]:
a9+np.array([[1,2,3,4]]).T

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [89]:
a6.T

array([[0, 2, 1],
       [1, 0, 2],
       [2, 1, 1]])

In [91]:
np.sqrt(a5)

array([[ 2.64575131, 28.26658805,  3.46410162,  2.64575131,  2.23606798],
       [ 1.73205081,  2.64575131,  2.44948974,  2.64575131,  1.73205081],
       [ 2.        ,  2.        ,  2.23606798,  1.41421356,  2.82842712],
       [ 2.44948974,  2.        ,  2.82842712,  2.        ,  2.        ],
       [ 2.        ,  2.64575131,  1.73205081,  2.82842712,  2.        ],
       [ 2.23606798,  1.73205081,  2.82842712,  2.44948974,  2.23606798]])

In [92]:
np.exp(a5)

<ipython-input-92-4ed31d3941a0>:1: RuntimeWarning: overflow encountered in exp
  np.exp(a5)


array([[1.09663316e+03,            inf, 1.62754791e+05, 1.09663316e+03,
        1.48413159e+02],
       [2.00855369e+01, 1.09663316e+03, 4.03428793e+02, 1.09663316e+03,
        2.00855369e+01],
       [5.45981500e+01, 5.45981500e+01, 1.48413159e+02, 7.38905610e+00,
        2.98095799e+03],
       [4.03428793e+02, 5.45981500e+01, 2.98095799e+03, 5.45981500e+01,
        5.45981500e+01],
       [5.45981500e+01, 1.09663316e+03, 2.00855369e+01, 2.98095799e+03,
        5.45981500e+01],
       [1.48413159e+02, 2.00855369e+01, 2.98095799e+03, 4.03428793e+02,
        1.48413159e+02]])

In [93]:
np.log10(a5)

array([[0.84509804, 2.90254678, 1.07918125, 0.84509804, 0.69897   ],
       [0.47712125, 0.84509804, 0.77815125, 0.84509804, 0.47712125],
       [0.60205999, 0.60205999, 0.69897   , 0.30103   , 0.90308999],
       [0.77815125, 0.60205999, 0.90308999, 0.60205999, 0.60205999],
       [0.60205999, 0.84509804, 0.47712125, 0.90308999, 0.60205999],
       [0.69897   , 0.47712125, 0.90308999, 0.77815125, 0.69897   ]])

In [98]:
list(range(0,10))# not work floating support 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [103]:
np.arange(1,10,2.5)# floating jump value works in it is only difference otherwise same

array([1. , 3.5, 6. , 8.5])

In [106]:
np.linspace(2,3,num=20)# between twi number how no of numbers we want 

array([2.        , 2.05263158, 2.10526316, 2.15789474, 2.21052632,
       2.26315789, 2.31578947, 2.36842105, 2.42105263, 2.47368421,
       2.52631579, 2.57894737, 2.63157895, 2.68421053, 2.73684211,
       2.78947368, 2.84210526, 2.89473684, 2.94736842, 3.        ])

In [108]:
np.linspace(2,3)# by default 50 numbrs it gives

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [110]:
np.linspace(2,3,retstep=True)# retspace will give the jump size

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [112]:
np.logspace(2,4,num=4)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [114]:
np.eye(5)# identity Matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])